#!/usr/bin/sh
echo Errors are normal, just ignore them
echo -----------------------------------
adb_mac/adb shell pm uninstall --user 0 com.samsung.aasaservice
adb_mac/adb shell pm uninstall --user 0 com.google.android.setupwizard
adb_mac/adb shell pm uninstall --user 0 com.google.android.apps.restore
adb_mac/adb shell pm uninstall --user 0 android.auto_generated_rro_product__
adb_mac/adb shell pm uninstall --user 0 android.auto_generated_rro_vendor__
adb_mac/adb shell pm uninstall --user 0 com.android.egg
adb_mac/adb shell pm uninstall --user 0 com.google.android.configupdater
adb_mac/adb shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels
adb_mac/adb shell pm uninstall --user 0 com.dsi.ant.plugins.antplus
adb_mac/adb shell pm uninstall --user 0 com.dsi.ant.service.socket
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mapsagent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.ardrawing
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.arzone
adb_mac/adb shell pm uninstall --user 0 com.google.ar.zone
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.spdfnote
adb_mac/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.hole
adb_mac/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.corner
adb_mac/adb shell pm uninstall --user 0 com.sec.android.autodoodle.service
adb_mac/adb shell pm uninstall --user 0 com.android.dreams.basic
adb_mac/adb shell pm uninstall --user 0 com.sec.android.widgetapp.webmanual
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.motionphoto.viewer
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.visionintelligence
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.bixbyvision.framework
adb_mac/adb shell pm uninstall --user 0 com.android.calllogbackup
adb_mac/adb shell pm uninstall --user 0 com.sec.factory.cameralyzer
adb_mac/adb shell pm uninstall --user 0 com.android.chrome
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.chromecustomizations
adb_mac/adb shell pm uninstall --user 0 com.android.theme.color.cinnamon
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.circular.themepicker
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.circular.launcher
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.android
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.settings
adb_mac/adb shell pm uninstall --user 0 com.android.backupconfirm
adb_mac/adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb_mac/adb shell pm uninstall --user 0 com.android.sharedstoragebackup
adb_mac/adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.gsa
adb_mac/adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.common
adb_mac/adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos
adb_mac/adb shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastservice
adb_mac/adb shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastreceiver
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.wifi.recources
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.wifi.softap.recources
adb_mac/adb shell pm uninstall --user 0 android.autoinstalls.config.samsung
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.homemode
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.livestickers
adb_mac/adb shell pm uninstall --user 0 com.google.android.apps.turbo
adb_mac/adb shell pm uninstall --user 0 com.google.android.as
adb_mac/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.double
adb_mac/adb shell pm uninstall --user 0 com.android.printspooler
adb_mac/adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
adb_mac/adb shell pm uninstall --user 0 com.android.dreams.phototable
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.samsungapps
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.game.gametools
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.game.gamehome
adb_mac/adb shell pm uninstall --user 0 com.google.android.gm
adb_mac/adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb_mac/adb shell pm uninstall --user 0 com.google.android.syncadapters.calendar
adb_mac/adb shell pm uninstall --user 0 com.google.android.syncadapters.contacts
adb_mac/adb shell pm uninstall --user 0 com.google.android.gms.location.history
adb_mac/adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb_mac/adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb_mac/adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb_mac/adb shell pm uninstall --user 0 com.google.android.partnersetup
adb_mac/adb shell pm uninstall --user 0 com.google.android.apps.carrier.carrierwifi
adb_mac/adb shell pm uninstall --user 0 com.android.theme.color.green 
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mobileservice
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.dynamiclock
adb_mac/adb shell pm uninstall --user 0 com.hiya.star 
adb_mac/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.tall
adb_mac/adb shell pm uninstall --user 0 com.samsung.klmsagent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.knox.analytics.uploader
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.simplesharing
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.service.livedrawing
adb_mac/adb shell pm uninstall --user 0 com.google.android.apps.maps
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mdx.quickboard
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mdx.kit
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mdx
adb_mac/adb shell pm uninstall --user 0 com.facebook.katana
adb_mac/adb shell pm uninstall --user 0 com.facebook.services
adb_mac/adb shell pm uninstall --user 0 com.facebook.system 
adb_mac/adb shell pm uninstall --user 0 com.facebook.appmanager
adb_mac/adb shell pm uninstall --user 0 com.netflix.mediaclient
adb_mac/adb shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver
adb_mac/adb shell pm uninstall --user 0 com.google.android.cellbroadcastservice
adb_mac/adb shell pm uninstall --user 0 com.netflix.partner.activation
adb_mac/adb shell pm uninstall --user 0 com.android.theme.font.notoserifsource
adb_mac/adb shell pm uninstall --user 0 com.android.theme.color.ocean
adb_mac/adb shell pm uninstall --user 0 com.microsoft.skydrive
adb_mac/adb shell pm uninstall --user 0 com.microsoft.appmanager
adb_mac/adb shell pm uninstall --user 0 com.android.theme.color.orchid
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon.pebble
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.service.peoplestripe
adb_mac/adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb_mac/adb shell pm uninstall --user 0 com.android.theme.color.purple
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.ringtoneBR
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.launcher
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.themepicker
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.android
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon.roundedrect
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.svoiceime
adb_mac/adb shell pm uninstall --user 0 com.google.android.feedback
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.smartswitchassistant
adb_mac/adb shell pm uninstall --user 0 com.osp.app.signin
adb_mac/adb shell pm uninstall --user 0 com.sec.android.desktopmode.uiservice
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.spage
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.kidsinstaller
adb_mac/adb shell pm uninstall --user 0 com.sec.spp.push
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.smartsuggestions
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.sm.policy
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.cocktailbarservice
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.appseparation
adb_mac/adb shell pm uninstall --user 0 com.sec.location.nfwlocationprivacy
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider
adb_mac/adb shell pm uninstall --user 0 com.samsung.knox.securefolder
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.fast
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.location
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.smartcallprovider
adb_mac/adb shell pm uninstall --user 0 com.sec.android.easyMover.Agent 
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.service.stplatform
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.smartmirroring
adb_mac/adb shell pm uninstall --user 0 com.android.theme.color.space
adb_mac/adb shell pm uninstall --user 0 com.google.android.tts
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.service.aircommand
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon.squircle
adb_mac/adb shell pm uninstall --user 0 com.android.bips
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.easysetup
adb_mac/adb shell pm uninstall --user 0 com.google.mainline.telemetry
adb_mac/adb shell pm uninstall --user 0 com.android.traceur
adb_mac/adb shell pm uninstall --user 0 com.samsung.desktopsystemui
adb_mac/adb shell pm uninstall --user 0 com.samsung.systemui.bixby2
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.accessibility.talkback
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.icecone
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.taskedge
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon.taperedrect
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon.teardrop
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.tips
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.service.pentastic
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.service.airviewdictionary
adb_mac/adb shell pm uninstall --user 0 de.axelspringer.yana.zeropage
adb_mac/adb shell pm uninstall --user 0 com.android.theme.icon.vessel
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider
adb_mac/adb shell pm uninstall --user 0 com.diotek.sec.lookup.dictionary
adb_mac/adb shell pm uninstall --user 0 com.google.android.youtube
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.clipboardedge
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mdecservice
adb_mac/adb shell pm uninstall --user 0 com.sec.android.preloadinstaller
adb_mac/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.waterfall
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.bixby.service 
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.bixby.agent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.bixby.agent.dummy
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.bixby.wakeup
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.callbgprovider
adb_mac/adb shell pm uninstall --user 0 com.samsung.clipboardsaveservice
adb_mac/adb shell pm uninstall --user 0 com.android.wallpaperbackup
adb_mac/adb shell pm uninstall --user 0 com.sec.factory
adb_mac/adb shell pm uninstall --user 0 com.sec.android.diagmonagent
adb_mac/adb shell pm uninstall --user 0 com.android.dynsystem
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.aircommandmanager
adb_mac/adb shell pm uninstall --user 0 com.sec.factory.camera
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.fmm
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.fm
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.themestore
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.themecenter
adb_mac/adb shell pm uninstall --user 0 com.samsung.storyservice
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.sm.devicesecurity
adb_mac/adb shell pm uninstall --user 0 com.samsung.gpuwatchapp
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.providers.carrier
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.omcagent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.sdm.config
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.rubin.app
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.aware.service
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.sharelive
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.scloud
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.desktoplauncher
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard
adb_mac/adb shell pm uninstall --user 0 com.sec.location.nsflp2
adb_mac/adb shell pm uninstall --user 0 com.samsung.SMT
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.securitylogagent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.settings.bixby
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.shortcutbackupservice
adb_mac/adb shell pm uninstall --user 0 com.skms.android.agent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.beaconmanager
adb_mac/adb shell pm uninstall --user 0 com.sec.android.soagent
adb_mac/adb shell pm uninstall --user 0 com.wssyncmldm
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.stickercenter
adb_mac/adb shell pm uninstall --user 0 com.sec.android.systemupdate
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.quicktool
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.wlantest
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.aremoji
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.aremojieditor
adb_mac/adb shell pm uninstall --user 0 com.sec.android.mimage.avatarstickers
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.authfw
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.samsungpass
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.samsungpassautofill
adb_mac/adb shell pm uninstall --user 0 com.android.nfc 
adb_mac/adb shell pm uninstall --user 0 com.android.stk 
adb_mac/adb shell pm uninstall --user 0 com.android.stk2
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.da.daagent 
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.vtcamerasettings
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.apex
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.ipsgeofence
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.samsungpositioning
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload 
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.incall.contentprovider
adb_mac/adb shell pm uninstall --user 0 com.sec.unifiedwfc
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.stickercenter
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.visualars
adb_mac/adb shell pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe
adb_mac/adb shell pm uninstall --user 0 com.google.android.projection.gearhead
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.privateshare
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mateagent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.routines
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.service.tagservice
adb_mac/adb shell pm uninstall --user 0 com.android.apps.tag
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.sdk.handwriting
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.magnifier
adb_mac/adb shell pm uninstall --user 0 com.android.vending
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.reminder
adb_mac/adb shell pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
adb_mac/adb shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.ve.vebgm
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.knox.containeragent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.knox.containercore
adb_mac/adb shell pm uninstall --user 0 com.android.managedprovisioning
adb_mac/adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb_mac/adb shell pm uninstall --user 0 com.sec.epdgtestapp
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.setting.multisound
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.smartcapture
adb_mac/adb shell pm uninstall --user 0 com.android.providers.userdictionary
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.ledbackcover
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.forest
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.applinker
adb_mac/adb shell pm uninstall --user 0 com.samsung.adaptivebrightnessgo
adb_mac/adb shell pm uninstall --user 0 com.sec.bcservice
adb_mac/adb shell pm uninstall --user 0 com.sec.mhs.smarttethering
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.networkdiagnostic
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.sume.snn.service
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.sume.nn.service
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.tadownloader
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.brightnessbackupservice
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.server.wifi.mobilewips
adb_mac/adb shell pm uninstall --user 0 com.sem.factoryapp
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.svcagent
adb_mac/adb shell pm uninstall --user 0 com.sec.automation
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.DataCreate
adb_mac/adb shell pm uninstall --user 0 com.sec.android.easyonehand
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.safetyassurance
adb_mac/adb shell pm uninstall --user 0 com.sec.sve
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.personalization
adb_mac/adb shell pm uninstall --user 0 com.sec.android.app.bluetoothtest
adb_mac/adb shell pm uninstall --user 0 com.samsung.sec.android.application.csc
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.tapack.authfw
adb_mac/adb shell pm uninstall --user 0 com.sec.android.provider.badge
adb_mac/adb shell pm disable-user com.google.ar.core
adb_mac/adb shell pm uninstall --user 0 com.sec.android.provider.emergencymode
adb_mac/adb shell pm uninstall --user 0 com.android.carrierdefaultapp
adb_mac/adb shell pm uninstall --user 0 com.android.emergency
adb_mac/adb shell pm uninstall --user 0 com.samsung.safetyinformation
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.hdmapp
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.notes
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.notes.addons
adb_mac/adb shell pm uninstall --user 0 com.android.htmlviewer
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.updatecenter
adb_mac/adb shell pm uninstall --user 0 com.google.android.as.oss
adb_mac/adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.tapack.authfw
adb_mac/adb shell pm uninstall --user 0 com.android.cameraextensions
adb_mac/adb shell pm uninstall --user 0 com.android.wallpapercropper
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.providers.factory
adb_mac/adb shell pm uninstall --user 0 com.google.android.documentsui
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.gru 
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.singletake.service
adb_mac/adb shell pm uninstall --user 0 com.sec.vsim.ericssonnsds.webapp
adb_mac/adb shell pm uninstall --user 0 com.android.internal.systemui.onehanded.gestural
adb_mac/adb shell pm uninstall --user 0 com.android.providers.downloads.ui 
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.app.dofviewer
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.mcfds
adb_mac/adb shell pm uninstall --user 0 com.samsung.android.cidmanager
adb_mac/adb shell pm uninstall --user 0 com.sec.app.RilErrorNotifier
adb_mac/adb shell pm uninstall --user 0 com.samsung.rcs 
adb_mac/adb shell pm uninstall --user 0 com.monotype.android.font.foundation
adb_mac/adb shell pm uninstall --user 0 com.monotype.android.font.samsungone
adb_mac/adb shell settings put global window_animation_scale 0.8
adb_mac/adb shell settings put global transition_animation_scale 1.1
adb_mac/adb shell settings put global animator_duration_scale 1.25
adb_mac/adb install apks/dns.apk
adb_mac/adb install apks/browser.apk
adb_mac/adb install apks/systemuituner.apk
adb_mac/adb install apks/store.apk
sleep 1
adb_mac/adb shell pm grant com.zacharee1.systemuituner android.permission.WRITE_SECURE_SETTINGS
adb_mac/adb shell pm grant com.zacharee1.systemuituner android.permission.DUMP
adb_mac/adb shell pm grant com.zacharee1.systemuituner android.permission.PACKAGE_USAGE_STATS
echo rebooting.
adb_mac/adb reboot
sleep 5