#!/usr/bin/sh
echo Errors are normal, just ignore them
echo -----------------------------------
adb_lin/adb shell pm uninstall --user 0 com.samsung.aasaservice
adb_lin/adb shell pm uninstall --user 0 com.google.android.setupwizard
adb_lin/adb shell pm uninstall --user 0 com.google.android.apps.restore
adb_lin/adb shell pm uninstall --user 0 android.auto_generated_rro_product__
adb_lin/adb shell pm uninstall --user 0 android.auto_generated_rro_vendor__
adb_lin/adb shell pm uninstall --user 0 com.android.egg
adb_lin/adb shell pm uninstall --user 0 com.google.android.configupdater
adb_lin/adb shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels
adb_lin/adb shell pm uninstall --user 0 com.dsi.ant.plugins.antplus
adb_lin/adb shell pm uninstall --user 0 com.dsi.ant.service.socket
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.mapsagent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.ardrawing
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.arzone
adb_lin/adb shell pm uninstall --user 0 com.google.ar.zone
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.spdfnote
adb_lin/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.hole
adb_lin/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.corner
adb_lin/adb shell pm uninstall --user 0 com.sec.android.autodoodle.service
adb_lin/adb shell pm uninstall --user 0 com.android.dreams.basic
adb_lin/adb shell pm uninstall --user 0 com.sec.android.widgetapp.webmanual
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.motionphoto.viewer
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.visionintelligence
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.bixbyvision.framework
adb_lin/adb shell pm uninstall --user 0 com.android.calllogbackup
adb_lin/adb shell pm uninstall --user 0 com.sec.factory.cameralyzer
adb_lin/adb shell pm uninstall --user 0 com.android.chrome
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.chromecustomizations
adb_lin/adb shell pm uninstall --user 0 com.android.theme.color.cinnamon
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.circular.themepicker
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.circular.launcher
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.android
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.settings
adb_lin/adb shell pm uninstall --user 0 com.android.backupconfirm
adb_lin/adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb_lin/adb shell pm uninstall --user 0 com.android.sharedstoragebackup
adb_lin/adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.gsa
adb_lin/adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.common
adb_lin/adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos
adb_lin/adb shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastservice
adb_lin/adb shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastreceiver
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.wifi.recources
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.wifi.softap.recources
adb_lin/adb shell pm uninstall --user 0 android.autoinstalls.config.samsung
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.homemode
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.livestickers
adb_lin/adb shell pm uninstall --user 0 com.google.android.apps.turbo
adb_lin/adb shell pm uninstall --user 0 com.google.android.as
adb_lin/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.double
adb_lin/adb shell pm uninstall --user 0 com.android.printspooler
adb_lin/adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
adb_lin/adb shell pm uninstall --user 0 com.android.dreams.phototable
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.samsungapps
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.game.gametools
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.game.gamehome
adb_lin/adb shell pm uninstall --user 0 com.google.android.gm
adb_lin/adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb_lin/adb shell pm uninstall --user 0 com.google.android.syncadapters.calendar
adb_lin/adb shell pm uninstall --user 0 com.google.android.syncadapters.contacts
adb_lin/adb shell pm uninstall --user 0 com.google.android.gms.location.history
adb_lin/adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb_lin/adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb_lin/adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb_lin/adb shell pm uninstall --user 0 com.google.android.partnersetup
adb_lin/adb shell pm uninstall --user 0 com.google.android.apps.carrier.carrierwifi
adb_lin/adb shell pm uninstall --user 0 com.android.theme.color.green 
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.mobileservice
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.dynamiclock
adb_lin/adb shell pm uninstall --user 0 com.hiya.star 
adb_lin/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.tall
adb_lin/adb shell pm uninstall --user 0 com.samsung.klmsagent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.knox.analytics.uploader
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.simplesharing
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.service.livedrawing
adb_lin/adb shell pm uninstall --user 0 com.google.android.apps.maps
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.mdx.quickboard
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.mdx.kit
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.mdx
adb_lin/adb shell pm uninstall --user 0 com.facebook.katana
adb_lin/adb shell pm uninstall --user 0 com.facebook.services
adb_lin/adb shell pm uninstall --user 0 com.facebook.system 
adb_lin/adb shell pm uninstall --user 0 com.facebook.appmanager
adb_lin/adb shell pm uninstall --user 0 com.netflix.mediaclient
adb_lin/adb shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver
adb_lin/adb shell pm uninstall --user 0 com.google.android.cellbroadcastservice
adb_lin/adb shell pm uninstall --user 0 com.netflix.partner.activation
adb_lin/adb shell pm uninstall --user 0 com.android.theme.font.notoserifsource
adb_lin/adb shell pm uninstall --user 0 com.android.theme.color.ocean
adb_lin/adb shell pm uninstall --user 0 com.microsoft.skydrive
adb_lin/adb shell pm uninstall --user 0 com.microsoft.appmanager
adb_lin/adb shell pm uninstall --user 0 com.android.theme.color.orchid
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon.pebble
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.service.peoplestripe
adb_lin/adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb_lin/adb shell pm uninstall --user 0 com.android.theme.color.purple
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.ringtoneBR
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.launcher
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.themepicker
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.android
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon.roundedrect
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.svoiceime
adb_lin/adb shell pm uninstall --user 0 com.google.android.feedback
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.smartswitchassistant
adb_lin/adb shell pm uninstall --user 0 com.osp.app.signin
adb_lin/adb shell pm uninstall --user 0 com.sec.android.desktopmode.uiservice
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.spage
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.kidsinstaller
adb_lin/adb shell pm uninstall --user 0 com.sec.spp.push
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.smartsuggestions
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.sm.policy
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.cocktailbarservice
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.appseparation
adb_lin/adb shell pm uninstall --user 0 com.sec.location.nfwlocationprivacy
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider
adb_lin/adb shell pm uninstall --user 0 com.samsung.knox.securefolder
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.fast
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.location
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.smartcallprovider
adb_lin/adb shell pm uninstall --user 0 com.sec.android.easyMover.Agent 
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.service.stplatform
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.smartmirroring
adb_lin/adb shell pm uninstall --user 0 com.android.theme.color.space
adb_lin/adb shell pm uninstall --user 0 com.google.android.tts
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.service.aircommand
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon.squircle
adb_lin/adb shell pm uninstall --user 0 com.android.bips
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.easysetup
adb_lin/adb shell pm uninstall --user 0 com.google.mainline.telemetry
adb_lin/adb shell pm uninstall --user 0 com.android.traceur
adb_lin/adb shell pm uninstall --user 0 com.samsung.desktopsystemui
adb_lin/adb shell pm uninstall --user 0 com.samsung.systemui.bixby2
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.accessibility.talkback
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.icecone
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.taskedge
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon.taperedrect
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon.teardrop
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.tips
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.service.pentastic
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.service.airviewdictionary
adb_lin/adb shell pm uninstall --user 0 de.axelspringer.yana.zeropage
adb_lin/adb shell pm uninstall --user 0 com.android.theme.icon.vessel
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider
adb_lin/adb shell pm uninstall --user 0 com.diotek.sec.lookup.dictionary
adb_lin/adb shell pm uninstall --user 0 com.google.android.youtube
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.clipboardedge
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.mdecservice
adb_lin/adb shell pm uninstall --user 0 com.sec.android.preloadinstaller
adb_lin/adb shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.waterfall
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.bixby.service 
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.bixby.agent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.bixby.agent.dummy
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.bixby.wakeup
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.callbgprovider
adb_lin/adb shell pm uninstall --user 0 com.samsung.clipboardsaveservice
adb_lin/adb shell pm uninstall --user 0 com.android.wallpaperbackup
adb_lin/adb shell pm uninstall --user 0 com.sec.factory
adb_lin/adb shell pm uninstall --user 0 com.sec.android.diagmonagent
adb_lin/adb shell pm uninstall --user 0 com.android.dynsystem
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.aircommandmanager
adb_lin/adb shell pm uninstall --user 0 com.sec.factory.camera
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.fmm
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.fm
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.themestore
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.themecenter
adb_lin/adb shell pm uninstall --user 0 com.samsung.storyservice
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.sm.devicesecurity
adb_lin/adb shell pm uninstall --user 0 com.samsung.gpuwatchapp
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.providers.carrier
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.omcagent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.sdm.config
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.rubin.app
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.aware.service
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.sharelive
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.scloud
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.desktoplauncher
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard
adb_lin/adb shell pm uninstall --user 0 com.sec.location.nsflp2
adb_lin/adb shell pm uninstall --user 0 com.samsung.SMT
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.securitylogagent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.settings.bixby
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.shortcutbackupservice
adb_lin/adb shell pm uninstall --user 0 com.skms.android.agent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.beaconmanager
adb_lin/adb shell pm uninstall --user 0 com.sec.android.soagent
adb_lin/adb shell pm uninstall --user 0 com.wssyncmldm
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.stickercenter
adb_lin/adb shell pm uninstall --user 0 com.sec.android.systemupdate
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.quicktool
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.wlantest
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.aremoji
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.aremojieditor
adb_lin/adb shell pm uninstall --user 0 com.sec.android.mimage.avatarstickers
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.authfw
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.samsungpass
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.samsungpassautofill
adb_lin/adb shell pm uninstall --user 0 com.android.nfc 
adb_lin/adb shell pm uninstall --user 0 com.android.stk 
adb_lin/adb shell pm uninstall --user 0 com.android.stk2
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.da.daagent 
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.vtcamerasettings
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.apex
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.ipsgeofence
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.samsungpositioning
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload 
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.incall.contentprovider
adb_lin/adb shell pm uninstall --user 0 com.sec.unifiedwfc
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.stickercenter
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.visualars
adb_lin/adb shell pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe
adb_lin/adb shell pm uninstall --user 0 com.google.android.projection.gearhead
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.privateshare
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.mateagent
adb_lin/adb shell cmd overlay enable com.android.theme.icon_pack.circular.android
adb_lin/adb shell cmd overlay enable com.android.theme.icon_pack.circular.settings
adb_lin/adb shell cmd overlay enable com.android.theme.icon_pack.circular.systemui
adb_lin/adb shell cmd overlay enable com.android.theme.color.black
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.routines
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.service.tagservice
adb_lin/adb shell pm uninstall --user 0 com.android.apps.tag
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.sdk.handwriting
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.magnifier
adb_lin/adb shell pm uninstall --user 0 com.sec.android.daemonapp
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.reminder
adb_lin/adb shell pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
adb_lin/adb shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.ve.vebgm
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.knox.containeragent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.knox.containercore
adb_lin/adb shell pm uninstall --user 0 com.android.managedprovisioning
adb_lin/adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb_lin/adb shell pm uninstall --user 0 com.sec.epdgtestapp
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.setting.multisound
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.smartcapture
adb_lin/adb shell pm uninstall --user 0 com.android.providers.userdictionary
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.app.ledbackcover
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.forest
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.applinker
adb_lin/adb shell pm uninstall --user 0 com.samsung.adaptivebrightnessgo
adb_lin/adb shell pm uninstall --user 0 com.sec.bcservice
adb_lin/adb shell pm uninstall --user 0 com.sec.mhs.smarttethering
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.networkdiagnostic
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.sume.snn.service
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.sume.nn.service
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.tadownloader
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.brightnessbackupservice
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.server.wifi.mobilewips
adb_lin/adb shell pm uninstall --user 0 com.sem.factoryapp
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.svcagent
adb_lin/adb shell pm uninstall --user 0 com.sec.automation
adb_lin/adb shell pm disable-user com.samsung.android.honeyboard
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.messaging
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.DataCreate
adb_lin/adb shell pm uninstall --user 0 com.sec.android.easyonehand
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.safetyassurance
adb_lin/adb shell pm uninstall --user 0 com.sec.sve
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.personalization
adb_lin/adb shell pm uninstall --user 0 com.sec.android.app.bluetoothtest
adb_lin/adb shell pm uninstall --user 0 com.samsung.sec.android.application.csc
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.tapack.authfw
adb_lin/adb shell pm uninstall --user 0 com.sec.android.provider.badge
adb_lin/adb shell pm disable-user com.google.ar.core
adb_lin/adb shell pm uninstall --user 0 com.sec.android.provider.emergencymode
adb_lin/adb shell pm disable-user com.android.carrierdefaultapp
adb_lin/adb shell pm uninstall --user 0 com.android.emergency
adb_lin/adb shell pm uninstall --user 0 com.samsung.safetyinformation
adb_lin/adb shell pm uninstall --user 0 com.samsung.android.hdmapp
adb_lin/adb install apks/systemuituner.apk
adb_lin/adb shell pm grant com.zacharee1.systemuituner android.permission.WRITE_SECURE_SETTINGS
adb_lin/adb shell pm grant com.zacharee1.systemuituner android.permission.PACKAGE_USAGE_STATS
adb_lin/adb shell pm grant com.zacharee1.systemuituner android.permission.DUMP
adb_lin/adb install apks/messages.apk
adb_lin/adb install apks/accounts.apk
adb_lin/adb install apks/keyboard.apk
adb_lin/adb shell ime enable com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
adb_lin/adb shell ime set com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
adb_lin/adb install apks/browser.apk
adb_lin/adb install apks/store.apk
adb_lin/adb install apks/dns.apk
adb_lin/adb install apks/privacy.apk
adb_lin/adb install apks/calculator.apk
adb_lin/adb install apks/fdroidmodern.apk
adb_lin/adb shell settings put global window_animation_scale 0.75
adb_lin/adb shell settings put global transition_animation_scale 0.75
adb_lin/adb shell settings put global animator_duration_scale 0.75
adb_lin/adb install apks/weather.apk
echo rebooting.
adb_lin/adb reboot
timeout 5