echo Errors are normal, just ignore them
echo -----------------------------------
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.aasaservice
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.setupwizard
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.apps.restore
adb_win\adb.exe shell pm uninstall --user 0 android.auto_generated_rro_product__
adb_win\adb.exe shell pm uninstall --user 0 android.auto_generated_rro_vendor__
adb_win\adb.exe shell pm uninstall --user 0 com.android.egg
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.configupdater
adb_win\adb.exe shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels
adb_win\adb.exe shell pm uninstall --user 0 com.dsi.ant.plugins.antplus
adb_win\adb.exe shell pm uninstall --user 0 com.dsi.ant.service.socket
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mapsagent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.ardrawing
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.arzone
adb_win\adb.exe shell pm uninstall --user 0 com.google.ar.zone
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.spdfnote
adb_win\adb.exe shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.hole
adb_win\adb.exe shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.corner
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.autodoodle.service
adb_win\adb.exe shell pm uninstall --user 0 com.android.dreams.basic
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.widgetapp.webmanual
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.motionphoto.viewer
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.visionintelligence
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.bixbyvision.framework
adb_win\adb.exe shell pm uninstall --user 0 com.android.calllogbackup
adb_win\adb.exe shell pm uninstall --user 0 com.sec.factory.cameralyzer
adb_win\adb.exe shell pm uninstall --user 0 com.android.chrome
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.chromecustomizations
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.color.cinnamon
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.circular.themepicker
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.circular.launcher
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.filled.android
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.filled.settings
adb_win\adb.exe shell pm uninstall --user 0 com.android.backupconfirm
adb_win\adb.exe shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb_win\adb.exe shell pm uninstall --user 0 com.android.sharedstoragebackup
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.gsa
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.common
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastservice
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastreceiver
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.wifi.recources
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.wifi.softap.recources
adb_win\adb.exe shell pm uninstall --user 0 android.autoinstalls.config.samsung
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.homemode
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.livestickers
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.apps.turbo
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.as
adb_win\adb.exe shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.double
adb_win\adb.exe shell pm uninstall --user 0 com.android.printspooler
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.apps.tachyon
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
adb_win\adb.exe shell pm uninstall --user 0 com.android.dreams.phototable
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.samsungapps
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.game.gametools
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.game.gamehome
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.gm
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.syncadapters.calendar
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.syncadapters.contacts
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.gms.location.history
adb_win\adb.exe shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb_win\adb.exe shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.partnersetup
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.apps.carrier.carrierwifi
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.color.green 
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mobileservice
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.dynamiclock
adb_win\adb.exe shell pm uninstall --user 0 com.hiya.star 
adb_win\adb.exe shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.tall
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.klmsagent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.knox.analytics.uploader
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.simplesharing
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.service.livedrawing
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.apps.maps
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mdx.quickboard
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mdx.kit
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mdx
adb_win\adb.exe shell pm uninstall --user 0 com.facebook.katana
adb_win\adb.exe shell pm uninstall --user 0 com.facebook.services
adb_win\adb.exe shell pm uninstall --user 0 com.facebook.system 
adb_win\adb.exe shell pm uninstall --user 0 com.facebook.appmanager
adb_win\adb.exe shell pm uninstall --user 0 com.netflix.mediaclient
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.cellbroadcastservice
adb_win\adb.exe shell pm uninstall --user 0 com.netflix.partner.activation
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.font.notoserifsource
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.color.ocean
adb_win\adb.exe shell pm uninstall --user 0 com.microsoft.skydrive
adb_win\adb.exe shell pm uninstall --user 0 com.microsoft.appmanager
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.color.orchid
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon.pebble
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.service.peoplestripe
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.color.purple
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.ringtoneBR
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.launcher
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.themepicker
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon_pack.rounded.android
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon.roundedrect
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.svoiceime
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.feedback
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.smartswitchassistant
adb_win\adb.exe shell pm uninstall --user 0 com.osp.app.signin
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.desktopmode.uiservice
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.spage
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.kidsinstaller
adb_win\adb.exe shell pm uninstall --user 0 com.sec.spp.push
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.smartsuggestions
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.sm.policy
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.cocktailbarservice
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.appseparation
adb_win\adb.exe shell pm uninstall --user 0 com.sec.location.nfwlocationprivacy
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.knox.securefolder
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.fast
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.location
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.smartcallprovider
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.easyMover.Agent 
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.service.stplatform
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.smartmirroring
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.color.space
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.tts
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.service.aircommand
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon.squircle
adb_win\adb.exe shell pm uninstall --user 0 com.android.bips
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.easysetup
adb_win\adb.exe shell pm uninstall --user 0 com.google.mainline.telemetry
adb_win\adb.exe shell pm uninstall --user 0 com.android.traceur
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.desktopsystemui
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.systemui.bixby2
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.accessibility.talkback
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.icecone
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.taskedge
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon.taperedrect
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon.teardrop
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.tips
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.service.pentastic
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.service.airviewdictionary
adb_win\adb.exe shell pm uninstall --user 0 de.axelspringer.yana.zeropage
adb_win\adb.exe shell pm uninstall --user 0 com.android.theme.icon.vessel
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider
adb_win\adb.exe shell pm uninstall --user 0 com.diotek.sec.lookup.dictionary
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.youtube
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.clipboardedge
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mdecservice
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.preloadinstaller
adb_win\adb.exe shell pm uninstall --user 0 com.android.internal.display.cutout.emulation.waterfall
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.bixby.service 
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.bixby.agent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.bixby.agent.dummy
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.bixby.wakeup
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.callbgprovider
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.clipboardsaveservice
adb_win\adb.exe shell pm uninstall --user 0 com.android.wallpaperbackup
adb_win\adb.exe shell pm uninstall --user 0 com.sec.factory
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.diagmonagent
adb_win\adb.exe shell pm uninstall --user 0 com.android.dynsystem
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.aircommandmanager
adb_win\adb.exe shell pm uninstall --user 0 com.sec.factory.camera
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.fmm
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.fm
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.themestore
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.themecenter
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.storyservice
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.sm.devicesecurity
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.gpuwatchapp
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.providers.carrier
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.omcagent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.sdm.config
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.rubin.app
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.aware.service
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.sharelive
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.scloud
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.desktoplauncher
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard
adb_win\adb.exe shell pm uninstall --user 0 com.sec.location.nsflp2
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.SMT
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.securitylogagent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.settings.bixby
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.shortcutbackupservice
adb_win\adb.exe shell pm uninstall --user 0 com.skms.android.agent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.beaconmanager
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.soagent
adb_win\adb.exe shell pm uninstall --user 0 com.wssyncmldm
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.stickercenter
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.systemupdate
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.quicktool
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.wlantest
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.aremoji
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.aremojieditor
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.mimage.avatarstickers
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.authfw
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.samsungpass
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.samsungpassautofill
adb_win\adb.exe shell pm uninstall --user 0 com.android.nfc 
adb_win\adb.exe shell pm uninstall --user 0 com.android.stk 
adb_win\adb.exe shell pm uninstall --user 0 com.android.stk2
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.da.daagent 
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.vtcamerasettings
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.apex
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.ipsgeofence
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.samsungpositioning
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload 
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.incall.contentprovider
adb_win\adb.exe shell pm uninstall --user 0 com.sec.unifiedwfc
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.stickercenter
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.visualars
adb_win\adb.exe shell pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.projection.gearhead
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.privateshare
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mateagent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.routines
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.service.tagservice
adb_win\adb.exe shell pm uninstall --user 0 com.android.apps.tag
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.sdk.handwriting
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.magnifier
adb_win\adb.exe shell pm uninstall --user 0 com.android.vending
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.reminder
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.apps.setupwizard.searchselector
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.ve.vebgm
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.knox.containeragent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.knox.containercore
adb_win\adb.exe shell pm uninstall --user 0 com.android.managedprovisioning
adb_win\adb.exe shell pm uninstall --user 0 com.android.bookmarkprovider
adb_win\adb.exe shell pm uninstall --user 0 com.sec.epdgtestapp
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.setting.multisound
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.smartcapture
adb_win\adb.exe shell pm uninstall --user 0 com.android.providers.userdictionary
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.ledbackcover
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.forest
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.applinker
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.adaptivebrightnessgo
adb_win\adb.exe shell pm uninstall --user 0 com.sec.bcservice
adb_win\adb.exe shell pm uninstall --user 0 com.sec.mhs.smarttethering
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.networkdiagnostic
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.sume.snn.service
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.sume.nn.service
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.tadownloader
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.brightnessbackupservice
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.server.wifi.mobilewips
adb_win\adb.exe shell pm uninstall --user 0 com.sem.factoryapp
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.svcagent
adb_win\adb.exe shell pm uninstall --user 0 com.sec.automation
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.DataCreate
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.easyonehand
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.safetyassurance
adb_win\adb.exe shell pm uninstall --user 0 com.sec.sve
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.personalization
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.app.bluetoothtest
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.sec.android.application.csc
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.tapack.authfw
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.provider.badge
adb_win\adb.exe shell pm disable-user com.google.ar.core
adb_win\adb.exe shell pm uninstall --user 0 com.sec.android.provider.emergencymode
adb_win\adb.exe shell pm uninstall --user 0 com.android.carrierdefaultapp
adb_win\adb.exe shell pm uninstall --user 0 com.android.emergency
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.safetyinformation
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.hdmapp
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.notes
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.notes.addons
adb_win\adb.exe shell pm uninstall --user 0 com.android.htmlviewer
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.updatecenter
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.as.oss
adb_win\adb.exe shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.tapack.authfw
adb_win\adb.exe shell pm uninstall --user 0 com.android.cameraextensions
adb_win\adb.exe shell pm uninstall --user 0 com.android.wallpapercropper
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.providers.factory
adb_win\adb.exe shell pm uninstall --user 0 com.google.android.documentsui
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.gru 
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.singletake.service
adb_win\adb.exe shell pm uninstall --user 0 com.sec.vsim.ericssonnsds.webapp
adb_win\adb.exe shell pm uninstall --user 0 com.android.internal.systemui.onehanded.gestural
adb_win\adb.exe shell pm uninstall --user 0 com.android.providers.downloads.ui 
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.app.dofviewer
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.mcfds
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.android.cidmanager
adb_win\adb.exe shell pm uninstall --user 0 com.sec.app.RilErrorNotifier
adb_win\adb.exe shell pm uninstall --user 0 com.samsung.rcs 
adb_win\adb.exe shell pm uninstall --user 0 com.monotype.android.font.foundation
adb_win\adb.exe shell pm uninstall --user 0 com.monotype.android.font.samsungone
adb_win\adb.exe shell settings put global window_animation_scale 0.8
adb_win\adb.exe shell settings put global transition_animation_scale 1.1
adb_win\adb.exe shell settings put global animator_duration_scale 1.25
adb_win\adb.exe install apks\dns.apk
adb_win\adb.exe install apks\browser.apk
adb_win\adb.exe install apks\systemuituner.apk
adb_win\adb.exe install apks\store.apk
TIMEOUT 1
adb_win\adb.exe shell pm grant com.zacharee1.systemuituner android.permission.WRITE_SECURE_SETTINGS
adb_win\adb.exe shell pm grant com.zacharee1.systemuituner android.permission.DUMP
adb_win\adb.exe shell pm grant com.zacharee1.systemuituner android.permission.PACKAGE_USAGE_STATS
echo rebooting.
adb_win\adb.exe reboot
TIMEOUT 5